pipeline {
    agent any

    tools {

    }

    environment {

    }

    stages {
        stage('Fetch code') {
            steps {
                git branch: 'app', url: 'https://github.com/gilangjavier/episode03-cicd-container-digitalocean.git'
                
            }

        }
        stage('Build') {
            steps {
                sh 'mvn install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}